name: package_source_code

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create sourcecode.zip
        run: |
          zip -r sourcecode.zip ${{ github.workspace }}

      - name: Upload sourcecode.zip
        uses: actions/upload-artifact@master
        with:
          name: sourcecode.zip
          path: sourcecode.zip
